apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: nodejs-express-pipeline
  labels:
    app.kubernetes.io/version: "1.0"
  annotations:
    tekton.dev/pipelines.minVersion: "0.50.0"
    tekton.dev/tags: nodejs,express,npm,buildkit
    tekton.dev/displayName: "Node.js Express Build and Deploy Pipeline"
spec:
  description: >-
    This pipeline builds and deploys a Node.js Express application.
    It performs the following steps:
    1. Clones the source code from the Git repository
    2. Runs npm tests
    3. Builds a container image using BuildKit
    4. Pushes the image to the container registry
    5. Updates the deployment configuration

  params:
    - name: git-url
      type: string
      description: The git repository URL to clone from
    
    - name: git-revision
      type: string
      description: The git revision (branch, tag, or commit SHA) to checkout
      default: main
    
    - name: image-name
      type: string
      description: The fully qualified name of the container image to build (without tag)
    
    - name: image-tag
      type: string
      description: The tag to apply to the built container image
      default: latest
    
    - name: dockerfile-path
      type: string
      description: The path to the Dockerfile relative to the source root
      default: ./Dockerfile
    
    - name: build-context
      type: string
      description: The build context for the Docker build
      default: .
    
    - name: node-version
      type: string
      description: Node.js version to use for testing
      default: "18"

  workspaces:
    - name: source
      description: Workspace containing the source code to build
    
    - name: dockerconfig
      description: Docker config secret for authenticating to container registry
      optional: true

  tasks:
    # Task 1: Clone the Git repository
    - name: git-clone
      taskRef:
        resolver: git
        params:
          - name: url
            value: https://github.com/tektoncd/catalog.git
          - name: revision
            value: main
          - name: pathInRepo
            value: task/git-clone/0.9/git-clone.yaml
      params:
        - name: url
          value: $(params.git-url)
        - name: revision
          value: $(params.git-revision)
        - name: deleteExisting
          value: "true"
      workspaces:
        - name: output
          workspace: source

    # Task 2: Run npm tests
    - name: npm-test
      runAfter:
        - git-clone
      taskRef:
        resolver: git
        params:
          - name: url
            value: https://github.com/tektoncd/catalog.git
          - name: revision
            value: main
          - name: pathInRepo
            value: task/npm/0.1/npm.yaml
      params:
        - name: PATH_CONTEXT
          value: .
        - name: ARGS
          value:
            - test
        - name: IMAGE
          value: node:$(params.node-version)-alpine
      workspaces:
        - name: source
          workspace: source

    # Task 3: Build container image with BuildKit
    - name: buildkit
      runAfter:
        - npm-test
      taskRef:
        resolver: git
        params:
          - name: url
            value: https://github.com/tektoncd/catalog.git
          - name: revision
            value: main
          - name: pathInRepo
            value: task/buildkit/0.1/buildkit.yaml
      params:
        - name: IMAGE
          value: $(params.image-name):$(params.image-tag)
        - name: DOCKERFILE
          value: $(params.dockerfile-path)
        - name: CONTEXT
          value: $(params.build-context)
        - name: INSECURE_REGISTRY
          value: "false"
      workspaces:
        - name: source
          workspace: source
        - name: dockerconfig
          workspace: dockerconfig

  finally:
    # Cleanup task that runs regardless of pipeline success/failure
    - name: cleanup
      taskSpec:
        steps:
          - name: cleanup-workspace
            image: alpine:3.18
            script: |
              #!/bin/sh
              echo "Pipeline execution completed"
              echo "Image: $(params.image-name):$(params.image-tag)"
              echo "Git Revision: $(params.git-revision)"
