apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: hello-world-service-demo
  annotations:
    description: "Self-managed pipeline for Node.js Express hello-world service"
spec:
  # ======================== PARAMETERS ========================
  params:
    # --- Source Code Parameters ---
    - name: git-url
      type: string
      description: "The Git repository URL to clone"
    
    - name: git-revision
      type: string
      description: "Git revision to checkout (branch, tag, or commit SHA)"
      default: "main"
    
    - name: git-branch
      type: string
      description: "Git branch name for reference"
      default: "main"
    
    - name: project-root
      type: string
      description: "Relative path to project root within the repository"
      default: "."
    
    - name: sparse-checkout-directories
      type: string
      description: "Comma-separated list of directories for sparse checkout"
      default: ""
    
    # --- Container Image Parameters ---
    - name: image-name
      type: string
      description: "Full container image name with registry and tag (e.g., registry/repo:tag)"
    
    - name: image-repository-path
      type: string
      description: "Image repository path without registry or tag"
      default: "hello-world-service-demo"
    
    - name: dockerfile-path
      type: string
      description: "Path to Dockerfile relative to project root"
      default: "Dockerfile"
    
    # --- Build Configuration ---
    - name: build-args
      type: string
      description: "Docker build arguments (one per line, format: KEY=value)"
      default: ""
    
    # --- Resource Tracking Parameters ---
    - name: owner-identifier-label-key
      type: string
      description: "Label key for resource ownership tracking (enables event routing)"
      default: "pipeline-id"
    
    - name: owner-identifier-label-value
      type: string
      description: "Pipeline ID for event routing and resource tracking"
      default: ""
    
    - name: dockerfile-config-map-name
      type: string
      description: "ConfigMap name to store Dockerfile content for failure analysis"
      default: ""
    
    - name: dockerfile-config-map-namespace
      type: string
      description: "Namespace for Dockerfile ConfigMap"
      default: "planton-cloud-pipelines"

  # ======================== WORKSPACES ========================
  workspaces:
    - name: source
      description: "Shared workspace for source code and build artifacts"
    
    - name: package-credentials
      description: "Workspace for package registry credentials (optional)"
      optional: true

  # ======================== TASKS ========================
  tasks:
    # -------------------- Task 1: Clone Repository --------------------
    - name: git-checkout
      taskRef:
        resolver: git
        params:
          - name: url
            value: "https://github.com/plantoncloud/tekton-hub.git"
          - name: revision
            value: "main"
          - name: pathInRepo
            value: "tasks/git-clone.yaml"
      params:
        - name: url
          value: $(params.git-url)
        - name: revision
          value: $(params.git-revision)
        - name: sparseCheckoutDirectories
          value: $(params.sparse-checkout-directories)
        - name: deleteExisting
          value: "true"
        - name: verbose
          value: "true"
        - name: depth
          value: "1"
      workspaces:
        - name: output
          workspace: source

    # -------------------- Task 2: Build and Push Image --------------------
    - name: build-image
      runAfter:
        - git-checkout
      taskRef:
        resolver: git
        params:
          - name: url
            value: "https://github.com/plantoncloud/tekton-hub.git"
          - name: revision
            value: "main"
          - name: pathInRepo
            value: "tasks/buildkit.yaml"
      params:
        - name: image
          value: $(params.image-name)
        - name: contextDir
          value: $(params.project-root)
        - name: dockerfilePath
          value: $(params.dockerfile-path)
        - name: buildArgs
          value: $(params.build-args)
        - name: cache
          value: "true"
        - name: push
          value: "true"
        - name: platforms
          value: ""
        - name: dockerfile-config-map-name
          value: $(params.dockerfile-config-map-name)
        - name: dockerfile-config-map-namespace
          value: $(params.dockerfile-config-map-namespace)
        - name: owner-identifier-label-key
          value: $(params.owner-identifier-label-key)
        - name: owner-identifier-label-value
          value: $(params.owner-identifier-label-value)
      workspaces:
        - name: source
          workspace: source
