---
apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: hello-world-service-demo-pipeline
  labels:
    app.kubernetes.io/version: "1.0"
    planton.cloud/service: hello-world-service-demo
    planton.cloud/language: nodejs
    planton.cloud/framework: express
  annotations:
    planton.cloud/description: "Self-managed Tekton pipeline for Node.js Express hello-world service"
    planton.cloud/build-method: dockerfile
spec:
  description: |
    This pipeline builds and tests a Node.js Express application.
    It performs the following steps:
    1. Clones the source code from GitHub
    2. Installs npm dependencies and runs tests
    3. Validates the Node.js application
    4. Builds a Docker image using BuildKit
    5. Pushes the image to the container registry

  params:
    # Standard Planton Cloud parameters
    - name: git-url
      type: string
      description: Git repository URL to clone
    
    - name: git-revision
      type: string
      description: Git revision (branch, tag, or commit SHA) to checkout
      default: main
    
    - name: image-url
      type: string
      description: Fully qualified image URL (registry/repository:tag)
    
    - name: dockerfile
      type: string
      description: Path to the Dockerfile relative to source root
      default: Dockerfile
    
    - name: context
      type: string
      description: Path to the build context relative to source root
      default: .
    
    # Node.js specific parameters
    - name: node-version
      type: string
      description: Node.js version to use for testing
      default: "18"
    
    - name: npm-test-command
      type: string
      description: npm command to run tests
      default: "npm test"

  workspaces:
    - name: source
      description: Workspace containing the source code
    
    - name: package-credentials
      description: Workspace containing package registry credentials (npm, etc.)
      optional: true

  tasks:
    # Task 1: Clone the repository
    - name: git-clone
      taskRef:
        resolver: git
        params:
          - name: url
            value: https://github.com/planton-cloud/tekton-hub.git
          - name: revision
            value: main
          - name: pathInRepo
            value: tasks/git-clone/0.9/git-clone.yaml
      workspaces:
        - name: output
          workspace: source
      params:
        - name: url
          value: $(params.git-url)
        - name: revision
          value: $(params.git-revision)
        - name: deleteExisting
          value: "true"

    # Task 2: Install dependencies and run tests
    - name: npm-test
      runAfter:
        - git-clone
      taskRef:
        resolver: git
        params:
          - name: url
            value: https://github.com/planton-cloud/tekton-hub.git
          - name: revision
            value: main
          - name: pathInRepo
            value: tasks/npm/0.1/npm.yaml
      workspaces:
        - name: source
          workspace: source
      params:
        - name: PATH_CONTEXT
          value: $(params.context)
        - name: ARGS
          value:
            - clean-install
            - "&&"
            - $(params.npm-test-command)
        - name: IMAGE
          value: "node:$(params.node-version)-alpine"

    # Task 3: Validate Node.js application structure
    - name: validate-nodejs-app
      runAfter:
        - npm-test
      taskSpec:
        description: Validates that the Node.js application has required files
        workspaces:
          - name: source
            description: Source code workspace
        steps:
          - name: validate
            image: node:18-alpine
            workingDir: $(workspaces.source.path)
            script: |
              #!/bin/sh
              set -e
              
              echo "=== Validating Node.js Application Structure ==="
              
              # Check for package.json
              if [ ! -f "package.json" ]; then
                echo "ERROR: package.json not found"
                exit 1
              fi
              echo "✓ package.json found"
              
              # Check for main entry point
              if [ ! -f "server.js" ] && [ ! -f "index.js" ] && [ ! -f "app.js" ]; then
                echo "WARNING: No standard entry point found (server.js, index.js, or app.js)"
              else
                echo "✓ Application entry point found"
              fi
              
              # Check for Dockerfile
              if [ ! -f "Dockerfile" ]; then
                echo "ERROR: Dockerfile not found"
                exit 1
              fi
              echo "✓ Dockerfile found"
              
              # Validate package.json syntax
              node -e "require('./package.json')" 2>/dev/null
              if [ $? -eq 0 ]; then
                echo "✓ package.json is valid JSON"
              else
                echo "ERROR: package.json has invalid syntax"
                exit 1
              fi
              
              # Check for dependencies
              if grep -q '"dependencies"' package.json; then
                echo "✓ Dependencies section found in package.json"
              fi
              
              # Display package info
              echo ""
              echo "=== Package Information ==="
              node -e "const pkg = require('./package.json'); console.log('Name:', pkg.name); console.log('Version:', pkg.version); console.log('Description:', pkg.description);"
              
              echo ""
              echo "✓ All validations passed"
      workspaces:
        - name: source
          workspace: source

    # Task 4: Build and push Docker image using BuildKit
    - name: buildkit
      runAfter:
        - validate-nodejs-app
      taskRef:
        resolver: git
        params:
          - name: url
            value: https://github.com/planton-cloud/tekton-hub.git
          - name: revision
            value: main
          - name: pathInRepo
            value: tasks/buildkit/0.1/buildkit.yaml
      workspaces:
        - name: source
          workspace: source
      params:
        - name: IMAGE
          value: $(params.image-url)
        - name: DOCKERFILE
          value: $(params.dockerfile)
        - name: CONTEXT
          value: $(params.context)
        - name: BUILDKIT_CLIENT_IMAGE
          value: moby/buildkit:v0.12.5-rootless
        - name: BUILDKIT_DAEMON_ADDRESS
          value: tcp://buildkitd.buildkit.svc.cluster.local:1234
        - name: BUILDKIT_CLIENT_CERTS
          value: /certs

  finally:
    # Cleanup task that runs regardless of pipeline success/failure
    - name: cleanup
      taskSpec:
        description: Cleanup workspace and log pipeline completion
        steps:
          - name: log-completion
            image: alpine:3.19
            script: |
              #!/bin/sh
              echo "=== Pipeline Execution Complete ==="
              echo "Pipeline: hello-world-service-demo-pipeline"
              echo "Timestamp: $(date -u +"%Y-%m-%dT%H:%M:%SZ")"
              echo "==================================="
