apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: hello-world-service-build-pipeline
  namespace: planton-cloud-pipelines
spec:
  description: Build-only pipeline for hello-world-service-demo (no deployment)
  params:
    - name: git-url
      type: string
      description: "The Git URL to clone"
    - name: git-revision
      type: string
      description: "Git revision to checkout"
      default: "main"
    - name: image-name
      type: string
      description: "The full destination image (registry/repo:tag)"
    - name: project-root
      type: string
      description: "Relative path to the project's root inside the cloned repo"
      default: "."
  
  workspaces:
    - name: source
      description: "Workspace where source code is cloned"

  tasks:
    ########################################################################
    # 1) Clone source from Git
    ########################################################################
    - name: git-clone
      taskRef:
        resolver: hub
        params:
          - name: name
            value: git-clone
          - name: version
            value: "0.9"
      params:
        - name: url
          value: $(params.git-url)
        - name: revision
          value: $(params.git-revision)
        - name: deleteExisting
          value: "true"
      workspaces:
        - name: output
          workspace: source

    ########################################################################
    # 2) Install NPM dependencies
    ########################################################################
    - name: npm-install
      runAfter: ["git-clone"]
      workspaces:
        - name: source
          workspace: source
      taskSpec:
        workspaces:
          - name: source
        steps:
          - name: install
            image: node:18-alpine
            workingDir: $(workspaces.source.path)/$(params.project-root)
            script: |
              #!/bin/sh
              set -ex
              
              echo "Installing npm dependencies..."
              npm ci
              
              echo "Dependencies installed successfully"

    ########################################################################
    # 3) Run npm build (if needed - for this simple app, just validate)
    ########################################################################
    - name: npm-build
      runAfter: ["npm-install"]
      workspaces:
        - name: source
          workspace: source
      taskSpec:
        workspace:
          - name: source
        steps:
          - name: build
            image: node:18-alpine
            workingDir: $(workspaces.source.path)/$(params.project-root)
            script: |
              #!/bin/sh
              set -ex
              
              echo "Validating Node.js application..."
              node -c server.js
              
              echo "Running tests..."
              npm test
              
              echo "Build validation completed successfully"

    ########################################################################
    # 4) Build Docker image
    ########################################################################
    - name: docker-build
      runAfter: ["npm-build"]
      taskRef:
        resolver: hub
        params:
          - name: name
            value: kaniko
          - name: version
            value: "0.6"
      params:
        - name: IMAGE
          value: $(params.image-name)
        - name: DOCKERFILE
          value: ./Dockerfile
        - name: CONTEXT
          value: $(workspaces.source.path)/$(params.project-root)
      workspaces:
        - name: source
          workspace: source

    ########################################################################
    # 5) Push Docker image (handled by kaniko in docker-build task)
    # Note: Kaniko builds and pushes in one step
    ########################################################################

