apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: hello-world-service-demo-pipeline
  labels:
    app.kubernetes.io/version: "1.0"
    planton.cloud/service: hello-world-service-demo
  annotations:
    description: "Build and push pipeline for Node.js Express hello-world-service-demo"
spec:
  params:
    # Standard parameters
    - name: git-repo-url
      type: string
      description: "Git repository URL"
    - name: git-revision
      type: string
      description: "Git revision (branch, tag, or commit SHA)"
      default: "main"
    - name: git-credential-secret-name
      type: string
      description: "Name of the Kubernetes secret containing Git credentials"
    - name: git-credential-secret-key
      type: string
      description: "Key in the secret containing the Git token"
      default: "token"
    - name: container-registry-url
      type: string
      description: "Container registry URL (e.g., gcr.io/my-project)"
    - name: container-image-repo-path
      type: string
      description: "Image repository path within registry"
    - name: container-image-tag
      type: string
      description: "Container image tag"
    - name: container-registry-credential-secret-name
      type: string
      description: "Name of the Kubernetes secret containing registry credentials"
    - name: container-registry-credential-secret-key
      type: string
      description: "Key in the secret containing the registry auth config"
      default: "config.json"
    # Additional parameters
    - name: dockerfile-path
      type: string
      description: "Path to Dockerfile relative to source root"
      default: "Dockerfile"
    - name: build-context
      type: string
      description: "Path to build context relative to source root"
      default: "."
    - name: node-version
      type: string
      description: "Node.js version for validation"
      default: "18"

  workspaces:
    - name: source
      description: "Workspace containing the source code"
    - name: package-credentials
      description: "Workspace containing package manager credentials"
      optional: true

  tasks:
    # Task 1: Clone the Git repository
    - name: git-clone
      taskRef:
        resolver: git
        params:
          - name: url
            value: https://github.com/planton-cloud/tekton-hub.git
          - name: revision
            value: main
          - name: pathInRepo
            value: tasks/git-clone/git-clone.yaml
      params:
        - name: url
          value: $(params.git-repo-url)
        - name: revision
          value: $(params.git-revision)
        - name: gitSecretName
          value: $(params.git-credential-secret-name)
        - name: gitSecretKey
          value: $(params.git-credential-secret-key)
      workspaces:
        - name: output
          workspace: source

    # Task 2: Validate Node.js project and install dependencies
    - name: npm-validate
      runAfter:
        - git-clone
      taskRef:
        resolver: git
        params:
          - name: url
            value: https://github.com/planton-cloud/tekton-hub.git
          - name: revision
            value: main
          - name: pathInRepo
            value: tasks/npm/validate.yaml
      params:
        - name: node-version
          value: $(params.node-version)
        - name: package-path
          value: "."
      workspaces:
        - name: source
          workspace: source

    # Task 3: Build container image using BuildKit
    - name: buildkit-build-push
      runAfter:
        - npm-validate
      taskRef:
        resolver: git
        params:
          - name: url
            value: https://github.com/planton-cloud/tekton-hub.git
          - name: revision
            value: main
          - name: pathInRepo
            value: tasks/buildkit/buildkit.yaml
      params:
        - name: IMAGE
          value: "$(params.container-registry-url)/$(params.container-image-repo-path):$(params.container-image-tag)"
        - name: DOCKERFILE
          value: $(params.dockerfile-path)
        - name: CONTEXT
          value: $(params.build-context)
        - name: REGISTRY_SECRET_NAME
          value: $(params.container-registry-credential-secret-name)
        - name: REGISTRY_SECRET_KEY
          value: $(params.container-registry-credential-secret-key)
        - name: PUSH
          value: "true"
      workspaces:
        - name: source
          workspace: source

  results:
    - name: git-commit
      description: "The commit SHA that was built"
      value: $(tasks.git-clone.results.commit)
    - name: git-url
      description: "The Git repository URL"
      value: $(tasks.git-clone.results.url)
    - name: image-digest
      description: "Digest of the built container image"
      value: $(tasks.buildkit-build-push.results.IMAGE_DIGEST)
    - name: image-url
      description: "Full URL of the pushed container image"
      value: $(tasks.buildkit-build-push.results.IMAGE_URL)
