apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: hello-world-service-demo-pipeline
  labels:
    app: hello-world-service-demo
    org: blueberry-labs
spec:
  description: |
    Build and deploy pipeline for hello-world-service-demo Node.js service.
    This pipeline clones the repository, installs dependencies, runs tests,
    and builds a container image using Kaniko.
  
  params:
    - name: repo-url
      type: string
      description: The git repository URL to clone
      default: https://github.com/sureshattaluri/hello-world-service-demo.git
    
    - name: revision
      type: string
      description: The git revision to checkout (branch, tag, sha, ref)
      default: main
    
    - name: image-name
      type: string
      description: The fully qualified image name (registry/repository:tag)
      default: gcr.io/planton-cloud/hello-world-service-demo
    
    - name: image-tag
      type: string
      description: The image tag to use
      default: latest
    
    - name: dockerfile-path
      type: string
      description: Path to the Dockerfile relative to the repository root
      default: ./Dockerfile
    
    - name: context-path
      type: string
      description: The build context path relative to the repository root
      default: .
  
  workspaces:
    - name: source
      description: Workspace where the git repository is cloned
    
    - name: package-credentials
      description: Workspace for package manager credentials (npm, etc.)
      optional: true
  
  tasks:
    # Task 1: Clone the git repository
    - name: git-checkout
      taskRef:
        resolver: hub
        params:
          - name: kind
            value: task
          - name: name
            value: git-clone
          - name: version
            value: "0.9"
      workspaces:
        - name: output
          workspace: source
      params:
        - name: url
          value: $(params.repo-url)
        - name: revision
          value: $(params.revision)
        - name: deleteExisting
          value: "true"
    
    # Task 2: Install dependencies and run tests
    - name: npm-test
      runAfter:
        - git-checkout
      workspaces:
        - name: source
          workspace: source
      taskSpec:
        workspaces:
          - name: source
        steps:
          - name: install-dependencies
            image: node:18-alpine
            workingDir: $(workspaces.source.path)
            script: |
              #!/bin/sh
              set -e
              echo "Installing npm dependencies..."
              npm ci
              echo "Dependencies installed successfully"
          
          - name: run-tests
            image: node:18-alpine
            workingDir: $(workspaces.source.path)
            script: |
              #!/bin/sh
              set -e
              echo "Running tests..."
              npm test
              echo "Tests completed successfully"
    
    # Task 3: Build and push container image with Kaniko
    - name: build-image
      runAfter:
        - npm-test
      taskRef:
        resolver: hub
        params:
          - name: kind
            value: task
          - name: name
            value: kaniko
          - name: version
            value: "0.7"
      workspaces:
        - name: source
          workspace: source
        - name: dockerconfig
          workspace: package-credentials
      params:
        - name: IMAGE
          value: $(params.image-name):$(params.image-tag)
        - name: DOCKERFILE
          value: $(params.dockerfile-path)
        - name: CONTEXT
          value: $(params.context-path)
        - name: BUILDER_IMAGE
          value: gcr.io/kaniko-project/executor:v1.23.2
        - name: EXTRA_ARGS
          value:
            - --cache=true
            - --cache-ttl=24h
            - --compressed-caching=false
            - --snapshot-mode=redo
            - --use-new-run
  
  finally:
    # Task to run regardless of pipeline success/failure
    - name: cleanup-notification
      taskSpec:
        steps:
          - name: notify
            image: alpine:3.18
            script: |
              #!/bin/sh
              echo "Pipeline execution completed"
              echo "Image: $(params.image-name):$(params.image-tag)"
              echo "Revision: $(params.revision)"
